# Fetching it from service provide name 
# spring:
#   application:
#     name: Config-Default

eureka:
  discovery:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
